"""Materialize LLM parameters into a real ``configs/exp/<name>.yaml`` file.

The access point to the framework is ``python -m jmbc.run exp=<name>`` — it
loads ``configs/exp/<name>.yaml``. Rather than pass a long dotlist of overrides,
we synthesize a *new experiment config* tailored to the request and run it by
name. The generated file is a persistent, human-editable, reproducible artifact.

How it derives from an existing template
----------------------------------------
jmbc's loader supports a single ``extends: <base>`` level. Base templates
(``rbc``/``ks``/``general``) have no ``extends``; derived presets such as
``ks_local`` declare ``extends: ks``. So to derive from *any* template we:

* walk its ``extends`` chain to the ultimate base,
* inline the bodies of every non-base ancestor (so their deltas are preserved),
* set ``extends: <base>`` on the generated file (keeping the loader's 1-level
  rule satisfied), and
* merge the user's overrides on top.

At load time jmbc reconstructs: ``base.yaml`` + ``<base>`` + inlined-preset
deltas + user overrides — i.e. exactly "the chosen template, tweaked".
"""
from __future__ import annotations

import copy
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Tuple

import yaml

import settings
import sim_spec

# Generated exp files are named with this prefix so they are easy to identify
# (and to exclude from the list of base templates offered to the LLM).
GEN_PREFIX = "dash-"

_HEADER = (
    "# Auto-generated by the JaxMARL-BC LLM dashboard from a natural-language\n"
    "# request. Safe to edit or delete. Run with:\n"
    "#   python -m jmbc.run exp={name} log.run_name={name}\n"
)


@dataclass
class GeneratedConfig:
    name: str            # exp selector == run_name
    path: Path           # configs/exp/<name>.yaml
    base_driver: str     # rbc|ks|general — drives output dir runs/<base_driver>/
    yaml_text: str
    config: Dict[str, Any]


def _load_yaml(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {}
    return yaml.safe_load(path.read_text()) or {}


def _deep_merge(dst: Dict[str, Any], src: Dict[str, Any]) -> Dict[str, Any]:
    """Recursively merge ``src`` into ``dst`` (src wins). Mutates and returns dst."""
    for k, v in src.items():
        if isinstance(v, dict) and isinstance(dst.get(k), dict):
            _deep_merge(dst[k], v)
        else:
            dst[k] = copy.deepcopy(v)
    return dst


def resolve_template(name: str) -> Tuple[str, Dict[str, Any]]:
    """Return (ultimate_base, inlined_body_of_intermediate_presets).

    ``inlined_body`` is everything the non-base ancestors add on top of the
    base, ordered so a child overrides its parent. The base itself is applied
    via ``extends`` and is *not* inlined.
    """
    files: List[Tuple[str, Dict[str, Any]]] = []
    cur = name
    seen = set()
    ext = None
    while cur and cur not in seen:
        seen.add(cur)
        d = _load_yaml(settings.EXP_DIR / f"{cur}.yaml")
        ext = d.pop("extends", None)
        d.pop("exp", None)  # we set exp explicitly to the base driver
        files.append((cur, d))
        cur = ext

    base = files[-1][0]
    inlined: Dict[str, Any] = {}
    # Non-base ancestors, parent-most first so the closest child wins.
    for _, body in reversed(files[:-1]):
        _deep_merge(inlined, body)
    return base, inlined


def _nest(dotlist_pairs: List[Tuple[str, Any]]) -> Dict[str, Any]:
    """['env.n_agents', 20] -> {'env': {'n_agents': 20}}."""
    out: Dict[str, Any] = {}
    for path, value in dotlist_pairs:
        parts = path.split(".")
        node = out
        for p in parts[:-1]:
            node = node.setdefault(p, {})
        node[parts[-1]] = value
    return out


def _overrides_nested(params: Dict[str, Any]) -> Dict[str, Any]:
    """Turn normalized params into a nested override dict (no 'exp' selector)."""
    pairs: List[Tuple[str, Any]] = []
    for name, value in params.items():
        if name in ("experiment", "extra_overrides"):
            continue
        p = sim_spec.PARAM_BY_NAME[name]
        pairs.append((p.path, value))
    for path, value in params.get("extra_overrides", {}).items():
        pairs.append((path, value))
    return _nest(pairs)


def build_config(params: Dict[str, Any]) -> Dict[str, Any]:
    """Return the generated experiment config dict (not yet written)."""
    params = sim_spec.normalize(params)
    base, inlined = resolve_template(params["experiment"])
    body = _deep_merge(inlined, _overrides_nested(params))
    # The run name is controlled by the runner (CLI `log.run_name=`), so drop
    # any inherited value to keep the generated file honest.
    if isinstance(body.get("log"), dict):
        body["log"].pop("run_name", None)
        if not body["log"]:
            body.pop("log")
    # `exp` fixes the driver + output subdir; `extends` pulls the base config.
    config: Dict[str, Any] = {"extends": base, "exp": base}
    _deep_merge(config, body)
    return config


def write_config(params: Dict[str, Any], name: str) -> GeneratedConfig:
    """Write ``configs/exp/<name>.yaml`` and return its descriptor."""
    config = build_config(params)
    base = config["exp"]
    path = settings.EXP_DIR / f"{name}.yaml"
    body_text = yaml.safe_dump(config, sort_keys=False, default_flow_style=False)
    text = _HEADER.format(name=name) + "\n" + body_text
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    return GeneratedConfig(name=name, path=path, base_driver=base,
                           yaml_text=text, config=config)


def preview_yaml(params: Dict[str, Any], name: str) -> str:
    """Render what the generated file *would* contain, without writing it."""
    config = build_config(params)
    return _HEADER.format(name=name) + "\n" + yaml.safe_dump(
        config, sort_keys=False, default_flow_style=False)


def list_generated() -> List[Path]:
    if not settings.EXP_DIR.exists():
        return []
    return sorted(settings.EXP_DIR.glob(f"{GEN_PREFIX}*.yaml"))


def cleanup_generated(keep: int = 50) -> int:
    """Delete all but the ``keep`` most recent generated configs. Returns #deleted."""
    files = sorted(list_generated(), key=lambda p: p.stat().st_mtime, reverse=True)
    removed = 0
    for p in files[keep:]:
        try:
            p.unlink()
            removed += 1
        except OSError:
            pass
    return removed
